version: 2.1

orbs:
  ruby: circleci/ruby@1.1.2
  node: circleci/node@2

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.0-node
    steps:
      - checkout
      - ruby/install-deps:
          with-cache: true
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
  test:
    docker:
      - image: cimg/ruby:3.0.0-node
      - image: circleci/postgres:11
        environment:
          POSTGRES_USER: photonia
          POSTGRES_DB: photonia_test
          POSTGRES_PASSWORD: password
    environment:
      BUNDLE_JOBS: "5"
      BUNDLE_RETRY: "3"
      PHOTONIA_DATABASE_URL: "postgres://photonia:password@127.0.0.1/"
      RAILS_ENV: test
      PAGER: cat
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      - run:
          name: Install PostgreSQL client
          command: |
            sudo apt update
            sudo apt install -y postgresql-client
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      # Run rspec in parallel
      - ruby/rspec-test
      # - ruby/rubocop-check
  deploy:
    docker:
      - image: cimg/ruby:3.0.0-node
    steps:
      - checkout
      - ruby/install-deps
      - add_ssh_keys:
          fingerprints:
            - $DEPLOY_SSH_KEY_FINGERPRINT
      - run:
          name: Capistrano Deploy
          command: bundle exec cap production deploy

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
