:scheduler:
  :schedule:
    sitemap_refresh:
      cron: "0 5 * * *" # 5:00 AM
      class: SitemapRefreshJob
    precompute_related_tags:
      cron: "10 3 * * *" # 3:10 AM
      class: PrecomputeRelatedTagsJob
